### ISSUE TITLE
nconf isn't available on module load

### ISSUE THREAD

**Issue by steve-lorimer** [lmarkus/Kraken_Example_Passport#1]
In `models/user.js` `DIFFICULTY` is loaded from `nconf` on module load.

```
DIFFICULTY = (nconf.get('auth') && nconf.get('bcrypt').difficulty) || 8;  //Retrieve the desired difficulty from the configuration. (Default = 8)
```

(note there is also a typo in the check for the section existing - the section is `bcrypt` not `auth`)

`DIFFICULTY` will always be `8` because at this moment in time (module load), `nconf` hasn't loaded the app's config file.

Try changing the config to have a different work factor, and logging it during the `pre('save')` function

```
console.log('nconf config: ' + JSON.stringify(nconf.get('bcrypt')));
console.log('using bcrypt work factor ' + DIFFICULTY);
```

**Comment by lmarkus** [comment]
Yep.
You're completely right on both counts.
Thanks!

**Comment by steve-lorimer** [comment]
No worries - thanks for the work! :)
