### ISSUE TITLE
Update example to 1.x version with controllers within folders

### ISSUE THREAD

**Issue by mikesparr** [lmarkus/Kraken_Example_Passport#5]
I just updated to latest version of Kraken and ported older app to it but the navigation is now not working. It's not clear what should be in the `res.render()` for views now since we remove the controller folder from path, do we now remove this from the view string?

If you build this Passport example from scratch using latest framework where controllers are now embedded within folders, the redirects fail.  It's not clear now how the following works:
- `controllers/account/index.js`
- `models/account.js`
- `public/templates/account/login.dust`
- `locales/US/en/account/login.dust`
- `lib/auth.js`

Within the auth.js file what would the redirect be if login form was in /account/login instead of /login ?

Within the `/account/index.js` what would the `res.render('view', model)` be? Now that we remove the main folder from the route in `router.get({skip controller dir now}:id, req, res, {...})`.

I try running and get the following error and have tried various combinations of redirect and view strings with or without folder name (i.e. '/account') and none working.  Thanks!

![screen shot 2015-06-15 at 10 24 08 am](https://cloud.githubusercontent.com/assets/5553105/8164791/cb5a728e-1348-11e5-96d1-fa80088656be.png)

**Comment by lmarkus** [comment]
Hey @mikesparr 
My example is pretty outdated at this point.

Check out the official 1.x example from the kraken team:
https://github.com/krakenjs/kraken-example-with-passport

**Comment by mikesparr** [comment]
Thanks. Darn Google still pulls up yours first so I didn't see that one.  So it looks like you create folders for each controller now with index.js default.  If I wanted `/account/login` URL, would I create `controllers/account/login.js` or nest another folder with `index.js` in it?
